// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqUJK64LsdzR2-OS6uKFBrhxgYHO6AOA',
    appId: '1:955823943443:web:7c4897a806c0106daef4e6',
    messagingSenderId: '955823943443',
    projectId: 'localhire-f3d28',
    authDomain: 'localhire-f3d28.firebaseapp.com',
    storageBucket: 'localhire-f3d28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkvaMU-cQ4P34LfQIEh7sOhWDhA3H5Yo',
    appId: '1:955823943443:android:a68cc8e01f998dcfaef4e6',
    messagingSenderId: '955823943443',
    projectId: 'localhire-f3d28',
    storageBucket: 'localhire-f3d28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCth16gaSgNgZpFboiEnnNGc8bZTZVusU8',
    appId: '1:955823943443:ios:eb85e9d65d3e65b6aef4e6',
    messagingSenderId: '955823943443',
    projectId: 'localhire-f3d28',
    storageBucket: 'localhire-f3d28.firebasestorage.app',
    iosBundleId: 'com.example.localhire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCth16gaSgNgZpFboiEnnNGc8bZTZVusU8',
    appId: '1:955823943443:ios:eb85e9d65d3e65b6aef4e6',
    messagingSenderId: '955823943443',
    projectId: 'localhire-f3d28',
    storageBucket: 'localhire-f3d28.firebasestorage.app',
    iosBundleId: 'com.example.localhire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyqUJK64LsdzR2-OS6uKFBrhxgYHO6AOA',
    appId: '1:955823943443:web:798bd1751df86321aef4e6',
    messagingSenderId: '955823943443',
    projectId: 'localhire-f3d28',
    authDomain: 'localhire-f3d28.firebaseapp.com',
    storageBucket: 'localhire-f3d28.firebasestorage.app',
  );
}
